config/routes.rb
Rails.application.routes.draw do
  # login/logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    #get 'ideas/index'
    #get 'ideas/show'
    #get 'ideas/new'
    #get 'ideas/edit'
  root 'ideas#index'  
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password validations: true
   
  validates :mail, presence: true, uniqueness: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :current_user
  before_action :require_sign_in!
  helper_method :signed_in?

  protect_from_forgery with: :exception

  def current_user
    remember_token = User.encrypt(cookies[:user_remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:user_remember_token)
  end

  def signed_in?
    @current_user.present?
  end

  private

    def require_sign_in!
      redirect_to login_path unless signed_in?
    end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
  end

  def show
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to ideas_path, notice: 'Success!'
    else
      flash[:alert] = 'Save error!'
      render :new
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to ideas_path
    else
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

  private
  
    def idea_params
      params.require(:idea).permit(:title, :content)
    end

  def find_idea_by_id
    Idea.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_sign_in!, only: [:new, :create]
	before_action :set_user, only: [:create]

	def new
	end

	def create
		if @user.authenticate(session_params[:password])
			sign_in(@user)
			redirect_to root_path
		else
			flash.now[:danger] = t('.flash.invalid_password')
			render :new
		end
	end

	def destroy
		sign_out
		redirect_to login_path
	end

	private

		def set_user
			@user = User.find_by!(mail: session_params[:mail])
		rescue
			flash.now[:danger] = t.('.flash.invalid_mail')
			render action: 'new'
		end

		def session_params
			params.require(:session).permit(:mail, :password)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_sign_in!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/ideas/_form.html.erb
<%= form_with model: @idea do |f| %>
  <div class="form_group pt-4 pb-3">
    <%= f.text_field :title, placeholder: "Write down your idea", class: "form-control" %>
  </div>

  <div class="form-group" >
    <%= f.text_area :content, placeholder: "Tell us more about your idea", rows: 7, class: "form-control" %>
  </div>

  <div class="text-center"> 
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center pt-5">Edit</h2>

      <%= render "form" %>

      <div class="text-left pb-2">
        <button type="button" class="btn btn-outline-secondary">
          <%= link_to "Delete", idea_path(@idea.id), method: 
          :delete, data: {confirm: "Are you sure to delete the post?"} %>
        </button>
      </div>
      <div class="test-left">
        <button type="button" class="btn btn-outline-secondary">
          <%= link_to "Back", ideas_path %>
        </button>
      </div>
  </div>
</div>

app/views/ideas/index.html.erb
<body>
  <div class="top">
    <div class="header text-center pt-5 pb-5">
      <h1 class="text-center">IdeaBrite</h1>
      <div="sub-title">Tell us your idea and get feedback</div>
        <div class="fixed-top text-right pr-3 pt-2">
          <button type="button" class="btn btn-outline-primary">
            <%= link_to "Post", new_idea_path %>
          </button>
        </div>
    </div>
      <div align="center">
        <% @ideas.each do |idea| %>
          <div class="card text-center mt-5 mb-5 col-sm-5 bg-dark text-white">
            <img class="card-img" src="..." alt="カードの画像">
              <div class="card-image-overlay">
                <div class="card-body pb-5">
                  <tr>
                    <th>
                      <h3 class="card-title"><%= idea.title %></h3>
                    </th>
                  </tr>
                  <tr>
                    <th>
                      <p class="card-text pb-5"><%= idea.content %></p>
                    </th>
                  </tr>
                    <th>
                      <%= link_to 'Edit', edit_idea_path(idea.id) %>
                    </th>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<body>

app/views/ideas/new.html.erb
<div>
  <div class="col-md-4 offset-md-4">
    <h2 class="text-center pt-5">What is your Idea?</h2>

      <%= render "form" %>

      <%= link_to "Back", ideas_path %>
  </div>
</div>

app/views/ideas/show.html.erb
<h1>Ideas#show</h1>
<p>Find me in app/views/ideas/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-expand-md.navbar-light pt-1" 
    style="background-color: #58b2f4;">
      <a class="navbar-brand ml-2 h1">IdeaBrite</a>
    </nav>
    <div class= "container">
      <% if flash[:notice] %>
        <p class="text-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="text-danger"><%= flash[:alert] %></p>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user, url: users_path do |f| %>
  <%= form_error(@user) %>
    <div class="form_group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form_group">
      <%= f.label :mail %>
      <%= f.text_field :mail %>
    </div>
    <div class="form_group">
      <%= f.label :password %>
      <%= f.text_field :password %>
    </div>
    <div class="form_gorup">
      <%= f.label :password_confirmation %>
      <%= f.text_fieled :password_confirmation %>
    </div>

    <div class="text-center">
      <%= f.submit "登録" class: "btn-btn-primary" %>
    </div>

<% end %>

app/views/users/new_html.erb
<%= form_with model: @user, url: users_path do |f| %>
  <%= form_error(@user) %>
    <div class="form_group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form_group">
      <%= f.label :mail %>
      <%= f.text_field :mail %>
    </div>
    <div class="form_group">
      <%= f.label :password %>
      <%= f.text_field :password %>
    </div>
    <div class="form_gorup">
      <%= f.label :password_confirmation %>
      <%= f.text_fieled :password_confirmation %>
    </div>

    <div class="text-center">
      <%= f.submit "登録" class: "btn-btn-primary" %>
    </div>

<% end %>